sun_node:
  ros__parameters:
    parentframe_id: map
    radus: 0.0
    mass: 19000000
    rayons: 3.9
    periode_revolutions: -1.0
    periode_rotations: -1.0
    childframe_id: soleil
merc_node:
  ros__parameters:
    parentframe_id: soleil
    childframe_id: mercure
    mass: 19000000
    radus: 6.5
    rayons: 2.43
    periode_revolutions: -2.0
    periode_rotations: -2.0
